name: release-binaries

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  release-binary-assets:
    permissions:
      contents: write
    needs: create-release
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: copyrite
#          tar: none
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

  release-linux-packages:
    permissions:
      contents: write
    needs: create-release
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y rpm debhelper build-essential
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build RPM package
        run: rpmbuild --define "_topdir $(pwd)/rpmbuild" --build-in-place --nodeps -bb pkg/rpm/copyrite.spec
      - name: Release RPM assets
        uses: softprops/action-gh-release@v2
        with:
          files: rpmbuild/RPMS/**/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Debian package
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        run: |
          cp -r pkg/debian .
          dpkg-buildpackage --build=binary --no-sign
      - name: Release Debian assets
        uses: softprops/action-gh-release@v2
        with:
          files: ../*.deb
